language: node_js
node_js:
- '8'
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
env:
  global:
    secure: UYH/MEsTa+L9VmXZV2DgSlW05CjQpbbOFawHGQW/LiQMGQP+CRhcYz1fxUycHsV20S2IoFHP5EVTFo+1LIGWceC/I2ZFgYZ3yYfx6pXJJQVGl4re520GV7JXBJ/kd/JLoMI9Gwc69x8CnucdZa+kiuXbExz+9hy9w54s2cgCR4mXk1Gd0hPGdxCboefFo5Hf2BaFT9I57SD/V4W/aek8slbWn3MpBRBacomyzdlf6PQVXvii0CUoqx9oejlpcLQA8uh3vRWwD84zjyPzDcM77c3fx7CtP9jii3QEl/+lLd4F3zxkRue8U3vMDbBqSFkdEfa0LIwaPdP740oLnCm1cAEfDzTqN7LFFBHm8w3YMRc6ENI1NlaFT76uR0oDMXQrPVDXmBdyqsP8CJF/4Nav7BsxjvCuACcJ5DWspn33eV8GgI5t2Yn24NylrVoKje7LV0EnDjjU3N6FxByB/0arMs38M56gNPdkdjp6MMsRRGowum/e/V1kE9EU2PYkPs20ZCZyYYkMf8s7ICIqH3qo4Rj524UCemvqFrDqLIy35vBW08V1ac5cMNPbEkEdJc95/d8+st602f0CHhjT6LuNr5K6Hifn/hn7aLMFc7gF2E+OV/Qmjd7XT9WIgOqO9tlSB0rynmfuwCt5NPowwq9gC+mRnM2kyVueT3kJkcYAUBA=
